project_id = "fsxoskcionoobxuepqeg"

[functions.notify-support-ticket]
verify_jwt = false

[functions.deal-ai-assistant]
verify_jwt = false

[functions.send-deal-email]
verify_jwt = false

[functions.daily-digest]
verify_jwt = false

[functions.elevenlabs-conversation-token]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.firecrawl-scrape]
verify_jwt = false

[functions.firecrawl-search]
verify_jwt = false

[functions.firecrawl-map]
verify_jwt = false

[functions.firecrawl-crawl]
verify_jwt = false

[functions.get-fmcsa-key]
verify_jwt = false
